# Podman Compose Configuration
# This file uses Containerfile (OCI standard) instead of Dockerfile
# All services use Containerfile for building images
# Usage: podman-compose -f podman-compose.yml up -d
# Install: pip install podman-compose
version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-auth
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: eadgequry-auth
      MYSQL_USER: authuser
      MYSQL_PASSWORD: authpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - edagequry-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: authuser
      PMA_PASSWORD: authpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - edagequry-net

  mysql-user-profile:
    image: mysql:8.0
    container_name: mysql-user-profile
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: eadgequry-user-profile
      MYSQL_USER: profileuser
      MYSQL_PASSWORD: profilepassword
    ports:
      - "3307:3306"
    volumes:
      - mysql-user-profile-data:/var/lib/mysql
    networks:
      - edagequry-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  phpmyadmin-user-profile:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-user-profile
    environment:
      PMA_HOST: mysql-user-profile
      PMA_PORT: 3306
      PMA_USER: profileuser
      PMA_PASSWORD: profilepassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8083:80"
    depends_on:
      - mysql-user-profile
    networks:
      - edagequry-net

  sonarqube-db:
    image: postgres:15-alpine
    container_name: sonarqube-postgres
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqube
    volumes:
      - sonarqube-db-data:/var/lib/postgresql/data
    networks:
      - edagequry-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sonar"]
      interval: 10s
      timeout: 5s
      retries: 5

  sonarqube:
    image: sonarqube:10.4-community
    container_name: sonarqube
    depends_on:
      sonarqube-db:
        condition: service_healthy
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube-db:5432/sonarqube
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube-data:/opt/sonarqube/data:Z
      - sonarqube-extensions:/opt/sonarqube/extensions:Z
      - sonarqube-logs:/opt/sonarqube/logs:Z
    ports:
      - "9000:9000"
    networks:
      - edagequry-net
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'wget -qO- http://localhost:9000/api/system/status | grep -q ''"status":"UP"'' || exit 1',
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Zookeeper - Required for Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - edagequry-net
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2181"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Kafka - Message Broker for Auth -> Notification communication
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
      - "29092:29092"
    networks:
      - edagequry-net
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "kafka-topics",
          "--bootstrap-server",
          "localhost:9092",
          "--list",
        ]
      interval: 10s
      timeout: 10s
      retries: 5

  # MySQL for Datasource Service
  mysql-datasource:
    image: mysql:8.0
    container_name: mysql-datasource
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: datasource_db
      MYSQL_USER: datasourceuser
      MYSQL_PASSWORD: datasourcepassword
    ports:
      - "3308:3306"
    volumes:
      - mysql-datasource-data:/var/lib/mysql
    networks:
      - edagequry-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # phpMyAdmin for Datasource Service
  phpmyadmin-datasource:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-datasource
    environment:
      PMA_HOST: mysql-datasource
      PMA_PORT: 3306
      PMA_USER: datasourceuser
      PMA_PASSWORD: datasourcepassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8088:80"
    depends_on:
      - mysql-datasource
    networks:
      - edagequry-net

  # MySQL for Chatbot Service
  mysql-chatbot:
    image: mysql:8.0
    container_name: mysql-chatbot
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: chatbot_db
      MYSQL_USER: chatbot_user
      MYSQL_PASSWORD: chatbot_password
    ports:
      - "3311:3306"
    volumes:
      - mysql-chatbot-data:/var/lib/mysql
    networks:
      - edagequry-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # phpMyAdmin for Chatbot Service
  phpmyadmin-chatbot:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-chatbot
    environment:
      PMA_HOST: mysql-chatbot
      PMA_PORT: 3306
      PMA_USER: chatbot_user
      PMA_PASSWORD: chatbot_password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8089:80"
    depends_on:
      - mysql-chatbot
    networks:
      - edagequry-net

  # Jenkins CI/CD Server
  # NOTE: For rootless Podman, socket path is: ${XDG_RUNTIME_DIR}/podman/podman.sock (e.g., /run/user/1000/podman/podman.sock)
  # For rootful Podman, socket path is: /run/podman/podman.sock
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins-cicd
    user: root
    # Removed 'privileged: true' - not needed in Podman and can cause issues
    # Podman handles capabilities and security differently than Docker
    ports:
      - "8982:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      # For rootful Podman (running as root):
      - /run/podman/podman.sock:/var/run/docker.sock:Z
      # For rootless Podman (running as regular user), replace above line with:
      # - ${XDG_RUNTIME_DIR}/podman/podman.sock:/var/run/docker.sock:Z
      # Or typically: /run/user/1000/podman/podman.sock:/var/run/docker.sock:Z
      - ./jenkins-jobs:/var/jenkins_jobs:Z
    environment:
      - JENKINS_OPTS=--prefix=/jenkins
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    networks:
      - edagequry-net
    healthcheck:
      test:
        ["CMD-SHELL", "curl -f http://localhost:8080/jenkins/login || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s

networks:
  edagequry-net:
    # Podman networking notes:
    # - For rootless Podman: Uses slirp4netns by default (no driver needed)
    # - For rootful Podman: Can use bridge driver (netavark or CNI)
    # - Removing explicit driver for better Podman compatibility
    driver: bridge # Remove this line if using rootless Podman

volumes:
  mysql-data:
  mysql-user-profile-data:
  mysql-datasource-data:
  mysql-chatbot-data:
  sonarqube-db-data:
  sonarqube-data:
  sonarqube-extensions:
  sonarqube-logs:
  jenkins-data:
